apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: engineering-platform
  name: platform-environment
  namespace: flux-system
data:
  availability: NON_HA
  capacityDecision: DEV-002
  capacityProfile: SINGLE_USER_MINIMAL
  environment: DEV
  storageBinding: minio-gen-1
  storageDeviation: DEV-001
