apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-storage-budget
  namespace: minio
spec:
  hard:
    persistentvolumeclaims: '1'
    requests.storage: 50Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-storage-budget
  namespace: monitoring
spec:
  hard:
    persistentvolumeclaims: '3'
    requests.storage: 13Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-storage-budget
  namespace: platform
spec:
  hard:
    persistentvolumeclaims: '2'
    requests.storage: 45Gi
