apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 24h
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.21.1
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 30m
  releaseName: cert-manager
  serviceAccountName: cert-manager-helm-reconciler
  timeout: 10m
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    crds:
      enabled: true
    prometheus:
      servicemonitor:
        enabled: false
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 30m
        memory: 64Mi
    cainjector:
      resources:
        limits:
          cpu: 300m
          memory: 256Mi
        requests:
          cpu: 30m
          memory: 64Mi
    startupapicheck:
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
    webhook:
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 20m
          memory: 64Mi
