apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: engineering-platform
  name: minio-tls
  namespace: minio
spec:
  commonName: minio.minio.svc.cluster.local
  dnsNames:
    - minio
    - minio.minio
    - minio.minio.svc
    - minio.minio.svc.cluster.local
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: dev-selfsigned
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 360h
  secretName: minio-tls
