apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: engineering-platform
  name: minio
  namespace: minio
spec:
  ports:
    - name: api
      port: 9000
      protocol: TCP
      targetPort: api
    - name: console
      port: 9001
      protocol: TCP
      targetPort: console
  selector:
    app.kubernetes.io/name: minio
  type: ClusterIP
