apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - foundation
  - cert-manager/controller
  - cert-manager/config
  - minio
  - observability/controller
  - observability/config
  - cnpg/controller
  - cnpg/database
  - etcd-backup
